[2023-02-10T15:28:57.619+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: cms_asp_noc.get_files manual__2023-02-10T15:28:32.560061+00:00 [queued]>
[2023-02-10T15:28:57.628+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: cms_asp_noc.get_files manual__2023-02-10T15:28:32.560061+00:00 [queued]>
[2023-02-10T15:28:57.629+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-10T15:28:57.630+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-02-10T15:28:57.631+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-10T15:28:57.641+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): get_files> on 2023-02-10 15:28:32.560061+00:00
[2023-02-10T15:28:57.650+0000] {standard_task_runner.py:55} INFO - Started process 43070 to run task
[2023-02-10T15:28:57.655+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'cms_asp_noc', 'get_files', 'manual__2023-02-10T15:28:32.560061+00:00', '--job-id', '1707', '--raw', '--subdir', 'DAGS_FOLDER/cms_upd.py', '--cfg-path', '/tmp/tmpg9opi5z2']
[2023-02-10T15:28:57.659+0000] {standard_task_runner.py:83} INFO - Job 1707: Subtask get_files
[2023-02-10T15:28:57.745+0000] {task_command.py:388} INFO - Running <TaskInstance: cms_asp_noc.get_files manual__2023-02-10T15:28:32.560061+00:00 [running]> on host 2886274f27ea
[2023-02-10T15:28:57.818+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cms_asp_noc
AIRFLOW_CTX_TASK_ID=get_files
AIRFLOW_CTX_EXECUTION_DATE=2023-02-10T15:28:32.560061+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-10T15:28:32.560061+00:00
[2023-02-10T15:28:58.054+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-02-10T15:28:58.070+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/cms_pg/updates.py", line 81, in check_all_files
    get_asp_pricing_updates()
  File "/opt/airflow/dags/cms_pg/updates.py", line 36, in get_asp_pricing_updates
    cursor.execute(f"select * from cms.asppricing_audit where cast(auditdate as date) = cast(now() as date)")
psycopg2.errors.UndefinedTable: relation "cms.asppricing_audit" does not exist
LINE 1: select * from cms.asppricing_audit where cast(auditdate as d...
                      ^

[2023-02-10T15:28:58.080+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=cms_asp_noc, task_id=get_files, execution_date=20230210T152832, start_date=20230210T152857, end_date=20230210T152858
[2023-02-10T15:28:58.091+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1707 for task get_files (relation "cms.asppricing_audit" does not exist
LINE 1: select * from cms.asppricing_audit where cast(auditdate as d...
                      ^
; 43070)
[2023-02-10T15:28:58.159+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-10T15:28:58.192+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
