[2023-03-06T16:04:41.857+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: cms_asp_noc.data_load scheduled__2023-03-03T00:00:00+00:00 [queued]>
[2023-03-06T16:04:41.926+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: cms_asp_noc.data_load scheduled__2023-03-03T00:00:00+00:00 [queued]>
[2023-03-06T16:04:41.942+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-06T16:04:41.954+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-06T16:04:41.956+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-06T16:04:41.993+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): data_load> on 2023-03-03 00:00:00+00:00
[2023-03-06T16:04:42.042+0000] {standard_task_runner.py:55} INFO - Started process 222 to run task
[2023-03-06T16:04:42.061+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'cms_asp_noc', 'data_load', 'scheduled__2023-03-03T00:00:00+00:00', '--job-id', '1939', '--raw', '--subdir', 'DAGS_FOLDER/cms_upd.py', '--cfg-path', '/tmp/tmp_b1b19xw']
[2023-03-06T16:04:42.069+0000] {standard_task_runner.py:83} INFO - Job 1939: Subtask data_load
[2023-03-06T16:04:43.128+0000] {task_command.py:388} INFO - Running <TaskInstance: cms_asp_noc.data_load scheduled__2023-03-03T00:00:00+00:00 [running]> on host 2886274f27ea
[2023-03-06T16:04:43.397+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cms_asp_noc
AIRFLOW_CTX_TASK_ID=data_load
AIRFLOW_CTX_EXECUTION_DATE=2023-03-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-03T00:00:00+00:00
[2023-03-06T16:04:43.423+0000] {logging_mixin.py:137} INFO - ['section 508 version of July 2022 ASP NDC-HCPCS Crosswalk 060722.csv', 'section 508 version of July 2022 ASP Pricing File updated 120222.csv', 'section 508 version of July 2022 AWP NDC-HCPCS Crosswalk_060722.csv', 'section 508 version of July 2022 NOC NDC-HCPCS Crosswalk 060722.csv', 'section 508 version of July 2022 NOC Pricing File 060722.csv', 'section 508 version of July 2022 OPPS NDC-HCPCS Crosswalk 060722.csv', 'section 508 version of NDC-HCPCS Crosswalk Introduction Text 060722.csv']
[2023-03-06T16:04:43.424+0000] {logging_mixin.py:137} INFO - /opt/***/op_files/cms_zip_files/section 508 version of July 2022 ASP NDC-HCPCS Crosswalk 060722.csv
[2023-03-06T16:04:43.525+0000] {logging_mixin.py:137} INFO - success
[2023-03-06T16:04:43.529+0000] {logging_mixin.py:137} INFO - section 508 version of July 2022 ASP NDC-HCPCS Crosswalk 060722.csv
[2023-03-06T16:04:43.533+0000] {logging_mixin.py:137} INFO - excel file has been cleaned
[2023-03-06T16:04:43.621+0000] {logging_mixin.py:137} INFO -      Date_Uploaded   Code  ...    modification_time quarter
0       2023-03-06  90371  ...  2022-06-07 10:10:10       3
1       2023-03-06  90371  ...  2022-06-07 10:10:10       3
2       2023-03-06  90371  ...  2022-06-07 10:10:10       3
3       2023-03-06  90371  ...  2022-06-07 10:10:10       3
4       2023-03-06  90371  ...  2022-06-07 10:10:10       3
...            ...    ...  ...                  ...     ...
5378    2023-03-06  Q9967  ...  2022-06-07 10:10:10       3
5379    2023-03-06  Q9991  ...  2022-06-07 10:10:10       3
5380    2023-03-06  Q9991  ...  2022-06-07 10:10:10       3
5381    2023-03-06  Q9992  ...  2022-06-07 10:10:10       3
5382    2023-03-06  Q9992  ...  2022-06-07 10:10:10       3

[5383 rows x 14 columns]
[2023-03-06T16:04:43.836+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1901, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(ASP NDC-HCPCS, 2200) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/cms_pg/data_load_pg.py", line 112, in data_load_pg
    df.to_sql(table_name, engine_names, if_exists= 'replace', index= False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 2882, in to_sql
    method=method,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 728, in to_sql
    **engine_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1758, in to_sql
    dtype=dtype,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1650, in prep_table
    table.create()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 867, in create
    self._execute_create()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 853, in _execute_create
    self.table.create()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 962, in create
    bind._run_ddl_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3228, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2211, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 900, in visit_table
    include_foreign_key_constraints,  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1380, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 81, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1478, in _execute_ddl
    compiled,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1944, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2125, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1901, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(ASP NDC-HCPCS, 2200) already exists.

[SQL: 
CREATE TABLE "ASP NDC-HCPCS" (
	"Date_Uploaded" TEXT, 
	"Code" TEXT, 
	"Short_Description" TEXT, 
	"LABELER_NAME" TEXT, 
	"NDC2" TEXT, 
	"Drug_Name" TEXT, 
	"HCPCS_dosage" TEXT, 
	"PKG_SIZE" TEXT, 
	"PKG_QTY" BIGINT, 
	"BILLUNITS" FLOAT(53), 
	"BILLUNITSPKG" FLOAT(53), 
	"Date_created" TEXT, 
	modification_time TEXT, 
	quarter TEXT
)

]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
[2023-03-06T16:04:44.257+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=cms_asp_noc, task_id=data_load, execution_date=20230303T000000, start_date=20230306T160441, end_date=20230306T160444
[2023-03-06T16:04:44.550+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1939 for task data_load ((psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(ASP NDC-HCPCS, 2200) already exists.

[SQL: 
CREATE TABLE "ASP NDC-HCPCS" (
	"Date_Uploaded" TEXT, 
	"Code" TEXT, 
	"Short_Description" TEXT, 
	"LABELER_NAME" TEXT, 
	"NDC2" TEXT, 
	"Drug_Name" TEXT, 
	"HCPCS_dosage" TEXT, 
	"PKG_SIZE" TEXT, 
	"PKG_QTY" BIGINT, 
	"BILLUNITS" FLOAT(53), 
	"BILLUNITSPKG" FLOAT(53), 
	"Date_created" TEXT, 
	modification_time TEXT, 
	quarter TEXT
)

]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 222)
[2023-03-06T16:04:45.149+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-06T16:04:45.327+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
